### PR TITLE
Add `Social Media Policies` link to bottom of page

### LINKED ISSUE #220: Link to NSF's Comment Policy
## User story
As a lead for NSF social media, I want the aggregator page to include a link to NSF's Comment Policy, Disclaimer, Privacy and Copyright page (https://www.nsf.gov/social/policies.jsp) so that users will understand social media policies.  
  
## Acceptance criteria
- [ ]
- [ ]
- [ ]

## Definition of done
- [ ]
- [ ]
- [ ]

### PR DESCRIPTION
**Pull request by fureigh**
Fixes #220.

Changes proposed in this pull request:
* Add a link to [Social Media Policies](https://www.nsf.gov/social/policies.jsp) to the bottom of the page that we're currently using as the homepage.

### CODE REVIEW

**Comment by cmc333333** [comment]
Unfortunately, I don't see these changes when running locally:

screen shot 2018-04-16 at 11 12 24 am
screen shot 2018-04-16 at 11 12 11 am

Would you mind confirming that this is working on a fresh install?

**Comment by fureigh** [comment]
@cmc333333 Thanks for catching that! Ready for another look.

**Comment by fureigh** [comment]
From `nsf-demo.app.cloud.gov`:

screen shot 2018-04-19 at 4 56 11 pm

**Comment by fureigh** [comment]
Thank _you_, @cmc333333!

**Pull request merged**
